language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2.4
  - 2.3.0
env:
  matrix:
    - SPROCKETS_VERSION="~> 3.3.0"
    - SPROCKETS_VERSION="~> 3.4.0"
    - SPROCKETS_VERSION="~> 3.5.0"
    - SPROCKETS_VERSION="~> 4.0.0.beta2"
