language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
env:
  matrix:
    - SPROCKETS_VERSION="~> 3.3.0"
    - SPROCKETS_VERSION="~> 3.4.0"
    - SPROCKETS_VERSION="~> 3.5.0"
    - SPROCKETS_VERSION="~> 3.6.0"
    - SPROCKETS_VERSION="~> 3.7.0"
    - SPROCKETS_VERSION="~> 4.0.0.beta2"
